name: iOS (Capacitor) Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'tsconfig.json'
      - 'next.config.ts'
      - 'capacitor.config.ts'
      - '.github/workflows/ios-capacitor.yml'

jobs:
  ios:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build Next.js
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Install Capacitor iOS platform
        run: npm i -D @capacitor/ios

      - name: Sync Capacitor
        run: npx cap sync

      - name: Add iOS project (if missing)
        run: |
          if [ ! -d ios ]; then
            npx cap add ios
          fi

      - name: Set up Xcode signing (export options)
        run: |
          mkdir -p build
          cat > build/ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

      - name: Build iOS Archive
        working-directory: ios/App
        run: |
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -sdk iphoneos -archivePath ../../build/App.xcarchive clean archive CODE_SIGN_STYLE=Automatic | xcpretty && exit ${PIPESTATUS[0]}

      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath build/App.xcarchive -exportOptionsPlist build/ExportOptions.plist -exportPath build | xcpretty && exit ${PIPESTATUS[0]}

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: LandSafe-ipa
          path: build/*.ipa
